### ISSUE TITLE
When MaxInFlight is unset, local consumption very slow

### ISSUE THREAD

**Issue by abraithwaite** [segmentio/nsq-go#26]
Haven't investigated this yet, but when running nsq locally and using DefaultMaxInFlight, I was getting <1 msg/s coming through the `Messages()` channel.

**Comment by achille-roussel** [comment]
`DefaultMaxInFlight` is 1, which means every message has to get acked which may be happening on a timer (I'd have to review the code).

Feel free to make a PR to change it to a more practical value.

**Comment by abraithwaite** [comment]
I misunderstood the usage for the library.  I wasn't aware you have to ack the consumption with `Finish`.  I only read the docs for Consumer and not Message.  🤦‍♀️
